#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#GitHub Action Test
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: GithubActionsTest

on:  
  push:
    branches: 
      - master
jobs: 
  testing:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Print greeting from testing
      run: echo "Hello from testing docker-compose-study-project1"


  depoloy:
  
    runs-on: unbuntu-latest
    needs: [testing]
    
    steps:
    - name: Print greeting from deploy
      run: echo "Hello from deploy docker-compose-study-project1"
  
